const recipes = [
    {
        id: 1,
        name: "Margherita Pizza",
        category: "pizza veg offers",
        description: "Classic delight with 100% real mozzarella cheese",
        price: 299,
        rating: 4.2,
        deliveryTime: "30 mins",
        image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400",
        badge: "20% OFF",
        veg: true
    },
    {
        id: 2,
        name: "Chicken Burger",
        category: "burger nonveg",
        description: "Juicy grilled chicken with fresh vegetables",
        price: 199,
        rating: 4.5,
        deliveryTime: "25 mins",
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
        veg: false
    },
    {
        id: 3,
        name: "Hyderabadi Biryani",
        category: "biryani nonveg offers",
        description: "Aromatic basmati rice with tender chicken",
        price: 349,
        rating: 4.8,
        deliveryTime: "40 mins",
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400",
        badge: "15% OFF",
        veg: false
    },
    {
        id: 4,
        name: "Chocolate Cake",
        category: "dessert veg",
        description: "Rich and moist chocolate cake slice",
        price: 149,
        rating: 4.3,
        deliveryTime: "20 mins",
        image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400",
        veg: true
    },
    {
        id: 5,
        name: "Veg Hakka Noodles",
        category: "veg noodles",
        description: "Stir-fried noodles with fresh vegetables",
        price: 179,
        rating: 4.1,
        deliveryTime: "25 mins",
        image: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400",
        veg: true
    },
    {
        id: 6,
        name: "Paneer Tikka",
        category: "veg offers",
        description: "Grilled cottage cheese with spices",
        price: 249,
        rating: 4.6,
        deliveryTime: "30 mins",
        image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400",
        badge: "25% OFF",
        veg: true
    },
    {
        id: 7,
        name: "Mexican Tacos",
        category: "nonveg tacos",
        description: "Crispy tacos with spicy chicken filling",
        price: 229,
        rating: 4.4,
        deliveryTime: "28 mins",
        image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=400",
        veg: false
    },
    {
        id: 8,
        name: "BBQ Chicken Wings",
        category: "nonveg chicken offers",
        description: "Smoky BBQ flavored crispy wings",
        price: 279,
        rating: 4.7,
        deliveryTime: "35 mins",
        image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400",
        badge: "30% OFF",
        veg: false
    },
    {
        id: 9,
        name: "Caesar Salad",
        category: "veg salad",
        description: "Fresh greens with caesar dressing",
        price: 199,
        rating: 4.0,
        deliveryTime: "15 mins",
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400",
        veg: true
    },
    {
        id: 10,
        name: "Pepperoni Pizza",
        category: "pizza nonveg",
        description: "Classic pepperoni with extra cheese",
        price: 399,
        rating: 4.6,
        deliveryTime: "30 mins",
        image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400",
        veg: false
    },
    {
        id: 11,
        name: "Double Cheese Burger",
        category: "burger veg",
        description: "Twice the cheese, twice the fun",
        price: 249,
        rating: 4.4,
        deliveryTime: "20 mins",
        image: "https://images.unsplash.com/photo-1512152272829-e3139592d56f?w=400",
        veg: true
    },
    {
        id: 12,
        name: "Butter Chicken",
        category: "nonveg biryani",
        description: "Rich and creamy butter chicken with naan",
        price: 389,
        rating: 4.9,
        deliveryTime: "45 mins",
        image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=400",
        veg: false
    },
    {
        id: 13,
        name: "Tiramisu",
        category: "dessert veg",
        description: "Classic Italian coffee-flavored dessert",
        price: 199,
        rating: 4.7,
        deliveryTime: "15 mins",
        image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400",
        veg: true
    },
    {
        id: 14,
        name: "Schezwan Noodles",
        category: "veg noodles",
        description: "Spicy noodles with schezwan sauce",
        price: 189,
        rating: 4.2,
        deliveryTime: "25 mins",
        image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400",
        veg: true
    },
    {
        id: 15,
        name: "Fish and Chips",
        category: "nonveg",
        description: "Crispy fried fish with golden fries",
        price: 329,
        rating: 4.3,
        deliveryTime: "30 mins",
        image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400",
        veg: false
    },
    {
        id: 16,
        name: "Greek Salad",
        category: "veg salad",
        description: "Fresh cucumbers, tomatoes, and feta cheese",
        price: 219,
        rating: 4.5,
        deliveryTime: "15 mins",
        image: "https://images.unsplash.com/photo-1540420753420-319e34458d35?w=400",
        veg: true
    },
    {
        id: 17,
        name: "BBQ Paneer Pizza",
        category: "pizza veg offers",
        description: "Smoky BBQ sauce with paneer and onions",
        price: 349,
        rating: 4.4,
        deliveryTime: "35 mins",
        image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400",
        badge: "10% OFF",
        veg: true
    },
    {
        id: 18,
        name: "Mushroom Swiss Burger",
        category: "burger veg",
        description: "Juicy burger with sautéed mushrooms and swiss cheese",
        price: 269,
        rating: 4.5,
        deliveryTime: "25 mins",
        image: "https://images.unsplash.com/photo-1520072959219-c595dc870360?w=400",
        veg: true
    },
    {
        id: 19,
        name: "Mutton Biryani",
        category: "biryani nonveg",
        description: "Slow-cooked mutton with aromatic rice",
        price: 449,
        rating: 4.9,
        deliveryTime: "50 mins",
        image: "https://images.unsplash.com/photo-1589302168068-1c498282362b?w=400",
        veg: false
    },
    {
        id: 20,
        name: "Red Velvet Cupcake",
        category: "dessert veg",
        description: "Moist red velvet with cream cheese frosting",
        price: 89,
        rating: 4.4,
        deliveryTime: "10 mins",
        image: "https://images.unsplash.com/photo-1599785209707-a456fc133cbb?w=400",
        veg: true
    },
    {
        id: 21,
        name: "Pad Thai Noodles",
        category: "nonveg noodles",
        description: "Thai style stir-fried noodles with shrimp",
        price: 299,
        rating: 4.6,
        deliveryTime: "30 mins",
        image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400",
        veg: false
    },
    {
        id: 22,
        name: "Grilled Salmon",
        category: "nonveg offers",
        description: "Fresh salmon with lemon butter sauce",
        price: 499,
        rating: 4.8,
        deliveryTime: "35 mins",
        image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400",
        badge: "20% OFF",
        veg: false
    },
    {
        id: 23,
        name: "Spaghetti Carbonara",
        category: "nonveg",
        description: "Classic pasta with egg, cheese, and bacon",
        price: 349,
        rating: 4.7,
        deliveryTime: "25 mins",
        image: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400",
        veg: false
    },
    {
        id: 24,
        name: "Quinoa Salad",
        category: "veg salad",
        description: "Healthy quinoa with roasted vegetables",
        price: 249,
        rating: 4.3,
        deliveryTime: "20 mins",
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400",
        veg: true
    },
    {
        id: 25,
        name: "Veggie Supreme Pizza",
        category: "pizza veg",
        description: "Loaded with mushrooms, onions, and bell peppers",
        price: 369,
        rating: 4.5,
        deliveryTime: "30 mins",
        image: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=400",
        veg: true
    },
    {
        id: 26,
        name: "Bacon Beef Burger",
        category: "burger nonveg",
        description: "Beef patty with crispy bacon and BBQ sauce",
        price: 299,
        rating: 4.7,
        deliveryTime: "30 mins",
        image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400",
        veg: false
    },
    {
        id: 27,
        name: "Paneer Biryani",
        category: "biryani veg offers",
        description: "Aromatic rice with spiced paneer cubes",
        price: 299,
        rating: 4.4,
        deliveryTime: "40 mins",
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400",
        badge: "15% OFF",
        veg: true
    },
    {
        id: 28,
        name: "Apple Pie",
        category: "dessert veg",
        description: "Classic homemade apple pie",
        price: 159,
        rating: 4.5,
        deliveryTime: "20 mins",
        image: "https://images.unsplash.com/photo-1568571780765-9276ac5ad47a?w=400",
        veg: true
    },
    {
        id: 29,
        name: "Singapore Noodles",
        category: "veg noodles offers",
        description: "Thin rice noodles with curry powder and veggies",
        price: 209,
        rating: 4.2,
        deliveryTime: "25 mins",
        image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400",
        badge: "10% OFF",
        veg: true
    },
    {
        id: 30,
        name: "Fried Chicken Bucket",
        category: "nonveg chicken",
        description: "8 pieces of original recipe fried chicken",
        price: 599,
        rating: 4.8,
        deliveryTime: "30 mins",
        image: "https://images.unsplash.com/photo-1569058242253-92a9c71f9867?w=400",
        veg: false
    },
    {
        id: 31,
        name: "Penne Arabiata",
        category: "veg",
        description: "Pasta in a spicy red tomato sauce",
        price: 279,
        rating: 4.4,
        deliveryTime: "25 mins",
        image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400",
        veg: true
    },
    {
        id: 32,
        name: "Avocado Toast",
        category: "veg salad",
        description: "Sourdough bread topped with mashed avocado",
        price: 189,
        rating: 4.1,
        deliveryTime: "15 mins",
        image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400",
        veg: true
    },
    {
        id: 33,
        name: "Hawaiian Pizza",
        category: "pizza nonveg",
        description: "Topped with pineapple and ham",
        price: 349,
        rating: 4.2,
        deliveryTime: "30 mins",
        image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400",
        veg: false
    },
    {
        id: 34,
        name: "Veggie Burger",
        category: "burger veg offers",
        description: "Patty made from carrots, corn, and beans",
        price: 159,
        rating: 4.0,
        deliveryTime: "20 mins",
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=400",
        badge: "20% OFF",
        veg: true
    },
    {
        id: 35,
        name: "Egg Biryani",
        category: "nonveg biryani",
        description: "Basmati rice with hard-boiled eggs and spices",
        price: 249,
        rating: 4.3,
        deliveryTime: "35 mins",
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400",
        veg: false
    },
    {
        id: 36,
        name: "Mango Cheesecake",
        category: "dessert veg",
        description: "Creamy cheesecake with fresh mango pulp",
        price: 179,
        rating: 4.6,
        deliveryTime: "15 mins",
        image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400",
        veg: true
    },
    {
        id: 37,
        name: "Udon Noodles",
        category: "nonveg noodles",
        description: "Thick wheat noodles with seafood and broth",
        price: 349,
        rating: 4.5,
        deliveryTime: "30 mins",
        image: "https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=400",
        veg: false
    },
    {
        id: 38,
        name: "Chicken Kebab",
        category: "nonveg chicken offers",
        description: "Succulent grilled chicken skewers",
        price: 299,
        rating: 4.7,
        deliveryTime: "25 mins",
        image: "https://images.unsplash.com/photo-1594005191041-3d9697171561?w=400",
        badge: "25% OFF",
        veg: false
    },
    {
        id: 39,
        name: "Mac and Cheese",
        category: "veg",
        description: "Cheesy and comforting macaroni",
        price: 229,
        rating: 4.2,
        deliveryTime: "20 mins",
        image: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=400",
        veg: true
    },
    {
        id: 40,
        name: "Fruit Salad",
        category: "veg salad offers",
        description: "Assorted seasonal fresh fruits",
        price: 149,
        rating: 4.4,
        deliveryTime: "10 mins",
        image: "https://images.unsplash.com/photo-1490812978280-71704339b09f?w=400",
        badge: "15% OFF",
        veg: true
    },
    {
        id: 41,
        name: "Chicken Tikka Pizza",
        category: "pizza nonveg",
        description: "Spiced chicken cubes on a cheesy base",
        price: 399,
        rating: 4.7,
        deliveryTime: "35 mins",
        image: "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?w=400",
        veg: false
    },
    {
        id: 42,
        name: "Fish Burger",
        category: "nonveg",
        description: "Crispy fish fillet with tartar sauce",
        price: 229,
        rating: 4.3,
        deliveryTime: "25 mins",
        image: "https://images.unsplash.com/photo-1512152272829-e3139592d56f?w=400",
        veg: false
    },
    {
        id: 43,
        name: "Lucknowi Biryani",
        category: "nonveg biryani",
        description: "Delicate and aromatic Awadhi biryani",
        price: 399,
        rating: 4.8,
        deliveryTime: "45 mins",
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400",
        veg: false
    },
    {
        id: 44,
        name: "Brownie with Ice Cream",
        category: "dessert veg offers",
        description: "Warm chocolate brownie with vanilla scoop",
        price: 129,
        rating: 4.9,
        deliveryTime: "15 mins",
        image: "https://images.unsplash.com/photo-1564355808539-22fda35bcd3e?w=400",
        badge: "10% OFF",
        veg: true
    },
    {
        id: 45,
        name: "Ramen",
        category: "nonveg noodles",
        description: "Japanese noodle soup with pork and egg",
        price: 449,
        rating: 4.8,
        deliveryTime: "30 mins",
        image: "https://images.unsplash.com/photo-1557872245-741f4c666e11?w=400",
        veg: false
    },
    {
        id: 46,
        name: "Chicken Lollipop",
        category: "nonveg chicken",
        description: "Spicy and crispy chicken appetizers",
        price: 279,
        rating: 4.5,
        deliveryTime: "20 mins",
        image: "https://images.unsplash.com/photo-1567622789183-b2197bb1123a?w=400",
        veg: false
    },
    {
        id: 47,
        name: "Fettuccine Alfredo",
        category: "veg",
        description: "Pasta in a rich creamy white sauce",
        price: 329,
        rating: 4.6,
        deliveryTime: "25 mins",
        image: "https://images.unsplash.com/photo-1645112481338-35622a59f5f2?w=400",
        veg: true
    },
    {
        id: 48,
        name: "Caprese Salad",
        category: "veg salad",
        description: "Fresh mozzarella, tomatoes, and basil",
        price: 259,
        rating: 4.4,
        deliveryTime: "15 mins",
        image: "https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=400",
        veg: true
    },
    {
        id: 49,
        name: "Four Cheese Pizza",
        category: "pizza veg offers",
        description: "Mozzarella, Cheddar, Parmesan, and Gorgonzola",
        price: 449,
        rating: 4.8,
        deliveryTime: "30 mins",
        image: "https://images.unsplash.com/photo-1573821663912-569905455b1c?w=400",
        badge: "30% OFF",
        veg: true
    },
    {
        id: 50,
        name: "Crispy Paneer Burger",
        category: "burger veg",
        description: "Spicy fried paneer with lettuce and mayo",
        price: 189,
        rating: 4.3,
        deliveryTime: "20 mins",
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=400",
        veg: true
    },
    {
        id: 51,
        name: "Prawn Biryani",
        category: "nonveg biryani",
        description: "Spiced prawns layered with basmati rice",
        price: 499,
        rating: 4.7,
        deliveryTime: "45 mins",
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400",
        veg: false
    },
    {
        id: 52,
        name: "Red Velvet Cake",
        category: "dessert veg",
        description: "Whole cake with velvety texture",
        price: 649,
        rating: 4.8,
        deliveryTime: "60 mins",
        image: "https://images.unsplash.com/photo-1586788680434-30d3246718d0?w=400",
        veg: true
    },
    {
        id: 53,
        name: "Thai Green Curry",
        category: "nonveg offers",
        description: "Classic green curry with jasmine rice",
        price: 389,
        rating: 4.6,
        deliveryTime: "35 mins",
        image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400",
        badge: "20% OFF",
        veg: false
    },
    {
        id: 54,
        name: "Chilli Chicken",
        category: "nonveg chicken",
        description: "Indo-Chinese style spicy chicken",
        price: 259,
        rating: 4.4,
        deliveryTime: "25 mins",
        image: "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=400",
        veg: false
    },
    {
        id: 55,
        name: "Lasagna",
        category: "nonveg",
        description: "Layered pasta with meat sauce and cheese",
        price: 429,
        rating: 4.7,
        deliveryTime: "40 mins",
        image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=400",
        veg: false
    },
    {
        id: 56,
        name: "Waldorf Salad",
        category: "veg salad",
        description: "Apples, grapes, walnuts, and celery",
        price: 279,
        rating: 4.3,
        deliveryTime: "15 mins",
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400",
        veg: true
    },
    {
        id: 57,
        name: "Margherita Pizza XL",
        category: "pizza veg offers",
        description: "Extra large classic mozzarella pizza",
        price: 549,
        rating: 4.3,
        deliveryTime: "40 mins",
        image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400",
        badge: "15% OFF",
        veg: true
    },
    {
        id: 58,
        name: "Chicken Sandwich",
        category: "nonveg",
        description: "Grilled chicken breast in toasted bread",
        price: 179,
        rating: 4.2,
        deliveryTime: "20 mins",
        image: "https://images.unsplash.com/photo-1521390188846-e2a39973e847?w=400",
        veg: false
    },
    {
        id: 59,
        name: "Egg Fried Rice",
        category: "nonveg biryani",
        description: "Classic wok-tossed rice with eggs",
        price: 199,
        rating: 4.1,
        deliveryTime: "25 mins",
        image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400",
        veg: false
    },
    {
        id: 60,
        name: "Gulab Jamun",
        category: "dessert veg",
        description: "Two pieces of soft milk-solid balls in syrup",
        price: 79,
        rating: 4.9,
        deliveryTime: "10 mins",
        image: "https://images.unsplash.com/photo-1589114121004-ec9035dfbb2a?w=400",
        veg: true
    },
    {
        id: 61,
        name: "Miso Soup",
        category: "veg",
        description: "Traditional Japanese soybean paste soup",
        price: 129,
        rating: 4.0,
        deliveryTime: "10 mins",
        image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400",
        veg: true
    },
    {
        id: 62,
        name: "Tandoori Chicken",
        category: "nonveg chicken offers",
        description: "Half chicken marinated in yogurt and spices",
        price: 349,
        rating: 4.8,
        deliveryTime: "30 mins",
        image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400",
        badge: "25% OFF",
        veg: false
    },
    {
        id: 63,
        name: "Ravioli Spinach",
        category: "veg",
        description: "Stuffed pasta with spinach and ricotta",
        price: 369,
        rating: 4.5,
        deliveryTime: "30 mins",
        image: "https://images.unsplash.com/photo-1579684947550-22e94522589a?w=400",
        veg: true
    },
    {
        id: 64,
        name: "Coleslaw Salad",
        category: "veg salad",
        description: "Shredded cabbage and carrots in creamy mayo",
        price: 119,
        rating: 3.9,
        deliveryTime: "10 mins",
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400",
        veg: true
    },
    {
        id: 65,
        name: "Sushi Platter",
        category: "nonveg offers",
        description: "Assorted nigiri and maki (12 pieces)",
        price: 899,
        rating: 4.9,
        deliveryTime: "40 mins",
        image: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=400",
        badge: "10% OFF",
        veg: false
    }
];
